version: '3'
services:
  redis:
    image: redis:alpine
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      default:
        aliases:
          - redis-server
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    logging:
        driver: "json-file"
        options:
          max-size: "200k"
          max-file: "10"
    networks:
      default:
        aliases:
          - mongo-server
  core-api:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: .
      args:
        NPM_RUN_SCRIPT: ${CORE_NPM_RUN_SCRIPT}
    volumes:
      - ./:/srv/node-scripts/:cached
      - /srv/node-scripts/node_modules
    ports:
      - 4040:4444
      - 9229:9229
    environment:
      APP_NAME: ${APP_NAME}
      APP_ID: ${APP_ID}
      MONGO_DSN: ${MONGO_DSN}
      REDIS_DSN: ${REDIS_DSN}
      PUBLIC_SERVER_URL: ${PUBLIC_SERVER_URL}
      PARSE_SERVER_URL: ${PARSE_SERVER_URL}
      PARSE_SERVER_MASTER_KEY: ${PARSE_SERVER_MASTER_KEY}
      PARSE_SERVER_READ_ONLY_MASTER_KEY: ${PARSE_SERVER_READ_ONLY_MASTER_KEY}
      PARSE_SERVER_LOGS_FOLDER: ${PARSE_SERVER_LOGS_FOLDER}
      DASHBOARD_USER: ${DASHBOARD_USER}
      DASHBOARD_PASS: ${DASHBOARD_PASS}
      DASHBOARD_TEST_USER: ${DASHBOARD_TEST_USER}
      DASHBOARD_TEST_PASS: ${DASHBOARD_TEST_PASS}
      DASHBOARD_TEST_READONLY: ${DASHBOARD_TEST_READONLY}
      DASHBOARD_ALLOW_INSECURE_HTTP: ${DASHBOARD_ALLOW_INSECURE_HTTP}
      DASHBOARD_COOKIE_SESSION_SECRET: ${DASHBOARD_COOKIE_SESSION_SECRET}
      DASHBOARD_ORIGIN: ${DASHBOARD_ORIGIN}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      VERIFY_USER_EMAILS: ${VERIFY_USER_EMAILS}
      PREVENT_LOGIN_WITH_UNVERIFIED_EMAIL: ${PREVENT_LOGIN_WITH_UNVERIFIED_EMAIL}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_VERIFICATION_TEMPLATE: ${SENDGRID_VERIFICATION_TEMPLATE}
      SENDGRID_PASSWORD_RESET_TEMPLATE: ${SENDGRID_PASSWORD_RESET_TEMPLATE}
